[input.data]
path = "example/data/data.parquet"
values = "residual_nos_1"

[input.pred]
path = "example/data/pred.parquet"

[output]
path = "example/data/my_result.parquet"
values = "prediction"

[[dimensions]]
kind = "GenericExponential"
coord = ["age_mid"]
kernel = { radius = 0.7 }

[[dimensions]]
kind = "GenericTricubic"
coord = ["year_id"]
kernel = { exponent = 0.5 }

[[dimensions]]
kind = "CategoricalHierarchical"
coord = ["super_region_id", "region_id", "location_id"]
kernel = { radius = 0.7 }
