[input.data]
path = "example/data/data.parquet"
values = "residual_nos_1"

[input.pred]
path = "example/data/pred.parquet"

[output]
path = "example/data/result.parquet"
values = "prediction"

[[dimensions]]
kind = "Generic"
coords = ["age_mid"]
distance = { kind = "Euclidean" }
kernel = { kind = "Exponential", radius = 0.7 }

[[dimensions]]
kind = "Adaptive"
coords = ["year_id"]
distance = { kind = "Euclidean" }
kernel = { kind = "Tricubic", exponent = 0.5 }

[[dimensions]]
kind = "Categorical"
coords = ["super_region_id", "region_id", "location_id"]
distance = { kind = "Tree" }
kernel = { kind = "DepthCODEm", radius = 0.7 }
