[datasets]
data = "data.parquet"
pred = "pred.parquet"

[[dimensions]]
key = ["age"]
distance = { type = "Euclidean" }
kernel = { type = "Exponential", radius = 0.7 }

[[dimensions]]
key = ["year"]
distance = { type = "Euclidean" }
kernel = { type = "Tricubic", radius = 43.0, exponent = 0.5 }

[[dimensions]]
key = ["super_region_id", "region_id", "location_id"]
distance = { type = "Tree" }
kernel = { type = "DepthCODEm", radius = 0.7, maxlvl = 3 }
