[datasets]
data = "example/data/data.parquet"
pred = "example/data/pred.parquet"

[[dimensions]]
type = "Generic"
key = ["age_mid"]
distance = { type = "Euclidean" }
kernel = { type = "Exponential", radius = 0.7 }

[[dimensions]]
type = "Generic"
key = ["year_id"]
distance = { type = "Euclidean" }
kernel = { type = "Tricubic", radius = 43.0, exponent = 0.5 }

[[dimensions]]
type = "Categorical"
key = ["super_region_id", "region_id", "location_id"]
distance = { type = "Tree" }
kernel = { type = "DepthCODEm", radius = 0.7, maxlvl = 3 }
