[input.data]
path = "benches/small/data.parquet"
values = "values"

[input.pred]
path = "benches/small/pred.parquet"

[output]
path = "benches/small/my_result.parquet"
values = "prediction"

[[dimensions]]
kind = "Generic"
coords = ["age_mid"]
kernel = { kind = "Exponential", radius = 0.7 }

[[dimensions]]
kind = "Generic"
coords = ["year_id"]
kernel = { kind = "Tricubic", exponent = 0.5 }

[[dimensions]]
kind = "Categorical"
coords = ["super_region_id", "region_id", "location_id"]
kernel = { kind = "DepthCODEm", radius = 0.7 }
